spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pruebatia?createDatabaseIfNotExist=true&autoReconnect=true&serverTimezone=UTC
    username: root
    password: STEVEN2199
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html